; SGC Phase 3 — BLE + BHY2 + LED
[common]
monitor_speed = 115200
build_flags_common = 
	-DSGC_VERSION="2.0"
	-DBHY2_CFG_DELEGATE_FIFO_PARSE_CB_INFO_MGMT=0
	-std=gnu++17
	-Wall -Wextra -Wno-pedantic
	-Wno-sign-conversion
	-Wno-conversion
	-Wno-return-type
	-Os
	-I src
lib_deps_common = 
	ArduinoBLE
	https://github.com/arduino-libraries/Arduino_BHY2.git

[env:nicla]
platform = nordicnrf52
board = nicla_sense_me
framework = arduino
monitor_speed = ${common.monitor_speed}
build_flags = ${common.build_flags_common}
lib_deps = 
	${common.lib_deps_common}
lib_ldf_mode = chain
lib_compat_mode = strict
debug_tool = cmsis-dap
upload_protocol = cmsis-dap

[env:custom_pcb]
platform = nordicnrf52
board = nicla_sense_me
framework = arduino
monitor_speed = ${common.monitor_speed}
build_flags = ${common.build_flags_common}
lib_deps = 
	${common.lib_deps_common}
lib_ldf_mode = chain
lib_compat_mode = strict
debug_tool = jlink
upload_protocol = jlink
