/// Synthetic GS run loader for phone app testing.
///
/// Loads the JSON generated by `scripts/generate_gs_run.py` and
/// constructs a `DecompressResult` that can be directly passed to
/// `RunDetailScreen` for UI testing without a BLE device.
library;

import 'dart:convert';
import '../../processing/decompressor.dart';
import '../../models/sensor_frame.dart';

/// Load synthetic GS run from JSON and build a DecompressResult.
class SyntheticRunLoader {
  /// Parse a JSON string (from gs_run_synthetic.json) into a DecompressResult.
  static DecompressResult fromJson(String jsonString) {
    final data = jsonDecode(jsonString) as Map<String, dynamic>;
    final hdr = data['header'] as Map<String, dynamic>;
    final framesJson = data['frames'] as List<dynamic>;

    final header = RunHeader(
      formatVersion: hdr['formatVersion'] as int,
      armSide: hdr['armSide'] as int,
      startTimestamp: hdr['startTimestamp'] as int,
      baroTempC: (hdr['baroTempC'] as num).toDouble(),
      compressedSize: hdr['compressedSize'] as int,
      frameCount: hdr['frameCount'] as int? ?? 0,
      calAccuracy: hdr['calAccuracy'] as int? ?? 0,
    );

    final frames = framesJson.map((f) {
      final m = f as Map<String, dynamic>;
      return SensorFrame(
        msFromStart: m['msFromStart'] as int,
        qW: (m['qW'] as num).toDouble(),
        qX: (m['qX'] as num).toDouble(),
        qY: (m['qY'] as num).toDouble(),
        qZ: (m['qZ'] as num).toDouble(),
        laX: (m['laX'] as num).toDouble(),
        laY: (m['laY'] as num).toDouble(),
        laZ: (m['laZ'] as num).toDouble(),
        baroPressurePa: (m['baroPressurePa'] as num).toDouble(),
        baroAltitudeM: (m['baroAltitudeM'] as num).toDouble(),
        verticalSpeedMs: (m['verticalSpeedMs'] as num).toDouble(),
      );
    }).toList();

    final totalMs = frames.isNotEmpty ? frames.last.msFromStart : 0;
    return DecompressResult(
      header: header,
      frames: frames,
      frameCount: frames.length,
      totalDurationSec: totalMs / 1000.0,
    );
  }
}
